### ISSUE TITLE
Untraceable config number in nar_preprocess_adressa.py

### ISSUE THREAD

**Issue by Heng-xiu** [gabrielspmoreira/chameleon_recsys#11]
![Screenshot from 2020-02-01 16-21-06](https://user-images.githubusercontent.com/5138488/73599205-0477af80-450f-11ea-870e-29d3aa9828ed.png)

Hi there, 

Can anyone help me to find out where are these numbers come from? 
For example, '_elapsed_ms_since_last_click' is an untraceable config. I cannot figure out why we should fill **1371436** for stddev or **789935.7** for avg.

**Comment by gabrielspmoreira** [comment]
Hi. Those hardcoded stats (mean, stddev) are used to apply z-normalization on those numeric features, and came from the the first pre-processing step for Adressa dataset, using PySpark 
[nar_module/scripts/dataproc_preprocessing/nar_preprocessing_addressa_01_dataproc.ipynb ](https://github.com/gabrielspmoreira/chameleon_recsys/blob/master/nar_module/scripts/dataproc_preprocessing/nar_preprocessing_addressa_01_dataproc.ipynb ).
Ideally, they should be output to a file by the PySpark pipeline and then reused by the `nar_preprocess_adressa.py` instead of being hardcoded as they are now.

**Comment by gabrielspmoreira** [comment]
Hi. Those hardcoded stats (mean, stddev) are used to apply z-normalization on those numeric features, and came from the the first pre-processing step for Adressa dataset, using PySpark
nar_module/scripts/dataproc_preprocessing/nar_preprocessing_addressa_01_dataproc.ipynb .
Ideally, they should be output to a file by the PySpark pipeline and then reused by the nar_preprocess_adressa.py instead of being hardcoded as they are now.
