### ISSUE TITLE
Missing ‘eval_sessions_negative_samples.json’ in benchmarks modules

### ISSUE THREAD

**Issue by q710245300** [gabrielspmoreira/chameleon_recsys#13]
Hi，
![image](https://user-images.githubusercontent.com/29564485/86770049-abdeac80-c082-11ea-8af9-e0fc82fc6dd5.png)
Can anyone help me find out the two files marked by a red circle in "chameleon_recsys/nar_module/scripts/benchmarks/run_sr-gnn_adressa.sh", or how to run sr-gnn module.
Best,

**Comment by gabrielspmoreira** [comment]
Hi.
To generate the file for the `--eval_sessions_negative_samples_json_path`, you need to run first the training of the NAR module for the Adressa dataset (**nar_module/scripts/run_nar_train_adressa_local.sh**) with the `--save_eval_sessions_negative_samples` parameter. The is necessary because the negative samples are generated on-the-fly, as the NAR training processes the data incrementally (in temporal order).
Regarding to the `--acr_module_resources_path`, that file is generated after training the ACR module for Adressa (**acr_module/acr/acr_trainer_adressa.py**). It is a pickle with a tuple serialized containing information about the articles `(acr_label_encoders, articles_metadata_df, content_article_embeddings)`
