### ISSUE TITLE
Missing some objects from ACR module

### ISSUE THREAD

**Issue by VictorOF** [gabrielspmoreira/chameleon_recsys#14]
Hi. After [this commit](https://github.com/gabrielspmoreira/chameleon_recsys/commit/764f38b691375c947f3a2ff84f702be01ece8c89) it was removed some objects from the unloading process of acr module to work on kaggle files. But some references to it are in the code, throwing errors.
[Here](https://github.com/gabrielspmoreira/chameleon_recsys/blob/master/nar_module/nar/nar_trainer_gcom.py#L124) and [here](https://github.com/gabrielspmoreira/chameleon_recsys/blob/master/nar_module/nar/nar_trainer_gcom.py#L213).
I removed those lines and tried to execute, but I'm still getting errors. Is this error in code or am I running wrong?

**Comment by JonasISE** [comment]
@VictorOF , were you able to fix the issue?

**Comment by VictorOF** [comment]
@JonasISE I wasn't able to fix it, but I succeeded running on commit e7e43bcaf001954b1d2bdc80659f1ed681e5af44

**Comment by gabrielspmoreira** [comment]
Hi @JonasISE and @VictorOF . In fact, those lines pointed by @VictorOF were buggy, as they used unavailable resources (pickled label encoders) for the nar_trainer_gcom.py. I have commended those lines on commit [2e50af5](https://github.com/gabrielspmoreira/chameleon_recsys/commit/2e50af53009a72ed465abd72c2a65a4b13286901), because now the categorical features cardinalities are hard-coded in the features config dicts for the Gcom dataset.
